from pathlib import Path
from bot.config import EXERCISE_DIR


def _img(filename: str) -> Path:
    return EXERCISE_DIR / filename


WORKOUT_DATA = {
    "monday": {
        "display_name": "Понедельник — Грудь + Трицепс",
        "weekday": 0,
        "rest_seconds": 50,
        "exercises": [
            {
                "name": "Классические отжимания",
                "name_en": "Push-ups",
                "sets": 3,
                "reps": 15,
                "duration": 0,
                "image": _img("Push-ups.jpg"),
                "tip": "Следи за прямой спиной, тело — одна линия.",
            },
            {
                "name": "Широкие отжимания",
                "name_en": "Wide push-ups",
                "sets": 3,
                "reps": 12,
                "duration": 0,
                "image": _img("Wide push-ups.jpg"),
                "tip": "Руки шире плеч — акцент на грудь.",
            },
            {
                "name": "Узкие отжимания",
                "name_en": "Close grip push-ups",
                "sets": 3,
                "reps": 12,
                "duration": 0,
                "image": _img("Close grip push-ups.jpg"),
                "tip": "Руки вместе — акцент на трицепс.",
            },
            {
                "name": "Алмазные отжимания",
                "name_en": "Diamond push-ups",
                "sets": 3,
                "reps": 10,
                "duration": 0,
                "image": _img("Diamond push-ups.jpg"),
                "tip": "Указательные и большие пальцы образуют ромб.",
            },
            {
                "name": "Отжимания с ногами на возвышении",
                "name_en": "Elevated feet push-ups",
                "sets": 3,
                "reps": 10,
                "duration": 0,
                "image": _img("Elevated feet push-ups.jpg"),
                "tip": "Ноги на стуле или диване — акцент на верхнюю грудь.",
            },
        ],
    },
    "tuesday": {
        "display_name": "Вторник — Спина + Бицепс",
        "weekday": 1,
        "rest_seconds": 50,
        "exercises": [
            {
                "name": "Супермен (удержание 2 сек)",
                "name_en": "Superman hold",
                "sets": 3,
                "reps": 15,
                "duration": 0,
                "image": _img("Superman hold.jpg"),
                "tip": "Лёжа на животе, поднимай руки и ноги одновременно, удерживай 2 сек.",
            },
            {
                "name": "Обратные снежные ангелы",
                "name_en": "Reverse snow angels",
                "sets": 3,
                "reps": 15,
                "duration": 0,
                "image": _img("Reverse snow angels.jpg"),
                "tip": "Лёжа на животе, руки вдоль тела — медленно поднимай и разводи.",
            },
            {
                "name": "Тяга к столу",
                "name_en": "Table rows",
                "sets": 3,
                "reps": 12,
                "duration": 0,
                "image": _img("Table rows, Bodyweight rows.jpg"),
                "tip": "Ляг под стол, хватайся за край и тяни грудь вверх.",
            },
            {
                "name": "Разгибания спины на мате",
                "name_en": "Back extensions",
                "sets": 3,
                "reps": 15,
                "duration": 0,
                "image": _img("Back extensions.jpg"),
                "tip": "Лёжа на животе, поднимай только верхнюю часть тела.",
            },
            {
                "name": "Бицепсовые сгибания с полотенцем",
                "name_en": "Towel bicep curls",
                "sets": 3,
                "reps": 12,
                "duration": 0,
                "image": _img("Towel bicep curls.jpg"),
                "tip": "Наступи на полотенце, тяни концы вверх — имитация бицепсового сгибания.",
            },
        ],
    },
    "thursday": {
        "display_name": "Четверг — Плечи + Пресс",
        "weekday": 3,
        "rest_seconds": 50,
        "exercises": [
            {
                "name": "Отжимания пикой",
                "name_en": "Pike push-ups",
                "sets": 3,
                "reps": 12,
                "duration": 0,
                "image": _img("Pike push-ups.jpg"),
                "tip": "Таз поднят высоко вверх, опускай голову к полу.",
            },
            {
                "name": "Стойка у стены",
                "name_en": "Wall handstand hold",
                "sets": 3,
                "reps": 0,
                "duration": 20,
                "image": _img("Wall handstand hold.jpg"),
                "tip": "Упор на руки у стены, тело вертикально.",
            },
            {
                "name": "Медленные отжимания пикой с паузой",
                "name_en": "Pike push-ups slow",
                "sets": 3,
                "reps": 8,
                "duration": 0,
                "image": _img("Pike push-ups.jpg"),
                "tip": "Опускайся медленно, 3 сек вниз, пауза внизу 2 сек.",
            },
            {
                "name": "Планка",
                "name_en": "Plank",
                "sets": 3,
                "reps": 0,
                "duration": 40,
                "image": _img("Plank.jpg"),
                "tip": "Тело прямое, не поднимай и не опускай таз.",
            },
            {
                "name": "Велосипед",
                "name_en": "Bicycle crunches",
                "sets": 3,
                "reps": 20,
                "duration": 0,
                "image": _img("Bicycle crunches.jpg"),
                "tip": "Локоть тянется к противоположному колену.",
            },
            {
                "name": "Подъём ног лёжа",
                "name_en": "Lying leg raises",
                "sets": 3,
                "reps": 15,
                "duration": 0,
                "image": _img("Lying leg raises.jpg"),
                "tip": "Поясница прижата к полу, ноги поднимай медленно.",
            },
            {
                "name": "Русский твист",
                "name_en": "Russian twist",
                "sets": 3,
                "reps": 20,
                "duration": 0,
                "image": _img("Russian twist.jpg"),
                "tip": "Ноги подняты, корпус скручивай влево-вправо.",
            },
        ],
    },
    "saturday": {
        "display_name": "Суббота — Кор + Лёгкий низ тела",
        "weekday": 5,
        "rest_seconds": 50,
        "exercises": [
            {
                "name": "Ягодичный мостик",
                "name_en": "Glute bridge",
                "sets": 3,
                "reps": 20,
                "duration": 0,
                "image": _img("Glute bridge.jpg"),
                "tip": "Медленно, контролируемо. Сожми ягодицы наверху.",
            },
            {
                "name": "Подъём на носки",
                "name_en": "Calf raises",
                "sets": 3,
                "reps": 25,
                "duration": 0,
                "image": _img("Calf raises.jpg"),
                "tip": "Поднимайся высоко, задержись на секунду наверху.",
            },
            {
                "name": "Обратный выпад",
                "name_en": "Reverse lunges",
                "sets": 2,
                "reps": 10,
                "duration": 0,
                "image": _img("Reverse lunges.jpg"),
                "tip": "Шаг назад, колено не касается пола. 10 повт. каждой ногой.",
            },
            {
                "name": "Статический присед у стены",
                "name_en": "Wall sit",
                "sets": 3,
                "reps": 0,
                "duration": 30,
                "image": _img("Wall sit.jpg"),
                "tip": "Бёдра параллельны полу, спина прижата к стене.",
            },
            {
                "name": "Боковая планка",
                "name_en": "Side plank",
                "sets": 2,
                "reps": 0,
                "duration": 30,
                "image": _img("Side plank.jpg"),
                "tip": "30 сек на каждую сторону. Бёдра не провисают.",
            },
            {
                "name": "Скалолаз",
                "name_en": "Mountain climbers",
                "sets": 3,
                "reps": 20,
                "duration": 0,
                "image": _img("Mountain climbers.jpg"),
                "tip": "Медленный темп — тяни колено к груди поочерёдно.",
            },
        ],
    },
}

REST_DAYS = {
    2: "Среда — день отдыха. Дай мышцам восстановиться!\nМожно сделать лёгкую прогулку или стретчинг.",
    4: "Пятница — день отдыха. Дай мышцам восстановиться!\nМожно сделать лёгкую прогулку или стретчинг.",
    6: "Воскресенье — полное восстановление перед новой неделей.",
}

DAY_KEY_MAP = {
    0: "monday",
    1: "tuesday",
    2: None,
    3: "thursday",
    4: None,
    5: "saturday",
    6: None,
}

DAY_LABELS = {
    "monday": "Понедельник",
    "tuesday": "Вторник",
    "thursday": "Четверг",
    "saturday": "Суббота",
}
